# Numpy

In [1]:
import numpy as np

In [44]:
# 1차원 array 만들기
array_1d = np.array([1, 2, 3, 4, 5])
array_1d

array([1, 2, 3, 4, 5])

In [45]:
# 2차원 array 만들기
array_2d = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
# 3차원 array 만들기
array_3d = np.random.random((3, 5, 5))
array_3d

array([[[0.78124306, 0.1300197 , 0.86921043, 0.92209494, 0.52745922],
        [0.07855933, 0.16597771, 0.23564542, 0.67872353, 0.37138356],
        [0.1725117 , 0.00526412, 0.69183316, 0.86469604, 0.36029251],
        [0.29529103, 0.97578211, 0.97259359, 0.21586312, 0.8005228 ],
        [0.86362957, 0.44305729, 0.37908188, 0.20095063, 0.55507751]],

       [[0.09838673, 0.18295729, 0.0846903 , 0.59206498, 0.16599771],
        [0.38160939, 0.39074154, 0.24794729, 0.25552162, 0.71474695],
        [0.09615487, 0.89858105, 0.71646421, 0.65333859, 0.69674532],
        [0.70411562, 0.24781776, 0.58959206, 0.88468741, 0.76487236],
        [0.33666411, 0.6919754 , 0.06109793, 0.88078403, 0.98944564]],

       [[0.80526665, 0.16570409, 0.30919119, 0.47121225, 0.61869812],
        [0.52807722, 0.3368465 , 0.55757328, 0.6189414 , 0.76514993],
        [0.48365085, 0.35762613, 0.8807984 , 0.96222669, 0.65310254],
        [0.06791795, 0.73421459, 0.30026167, 0.14514145, 0.25058   ],
        [0.63343

In [47]:
# array 모양 확인하기
array_3d.shape

(3, 5, 5)

In [56]:
# 차원 순서 바꾸기
np.transpose(array_3d, (1, 2, 0))

array([[[0.78124306, 0.09838673, 0.80526665],
        [0.1300197 , 0.18295729, 0.16570409],
        [0.86921043, 0.0846903 , 0.30919119],
        [0.92209494, 0.59206498, 0.47121225],
        [0.52745922, 0.16599771, 0.61869812]],

       [[0.07855933, 0.38160939, 0.52807722],
        [0.16597771, 0.39074154, 0.3368465 ],
        [0.23564542, 0.24794729, 0.55757328],
        [0.67872353, 0.25552162, 0.6189414 ],
        [0.37138356, 0.71474695, 0.76514993]],

       [[0.1725117 , 0.09615487, 0.48365085],
        [0.00526412, 0.89858105, 0.35762613],
        [0.69183316, 0.71646421, 0.8807984 ],
        [0.86469604, 0.65333859, 0.96222669],
        [0.36029251, 0.69674532, 0.65310254]],

       [[0.29529103, 0.70411562, 0.06791795],
        [0.97578211, 0.24781776, 0.73421459],
        [0.97259359, 0.58959206, 0.30026167],
        [0.21586312, 0.88468741, 0.14514145],
        [0.8005228 , 0.76487236, 0.25058   ]],

       [[0.86362957, 0.33666411, 0.63343412],
        [0.44305729, 0.691

In [57]:
# 모양 바꾸기
np.reshape(array_3d, (3, 25))

array([[0.78124306, 0.1300197 , 0.86921043, 0.92209494, 0.52745922,
        0.07855933, 0.16597771, 0.23564542, 0.67872353, 0.37138356,
        0.1725117 , 0.00526412, 0.69183316, 0.86469604, 0.36029251,
        0.29529103, 0.97578211, 0.97259359, 0.21586312, 0.8005228 ,
        0.86362957, 0.44305729, 0.37908188, 0.20095063, 0.55507751],
       [0.09838673, 0.18295729, 0.0846903 , 0.59206498, 0.16599771,
        0.38160939, 0.39074154, 0.24794729, 0.25552162, 0.71474695,
        0.09615487, 0.89858105, 0.71646421, 0.65333859, 0.69674532,
        0.70411562, 0.24781776, 0.58959206, 0.88468741, 0.76487236,
        0.33666411, 0.6919754 , 0.06109793, 0.88078403, 0.98944564],
       [0.80526665, 0.16570409, 0.30919119, 0.47121225, 0.61869812,
        0.52807722, 0.3368465 , 0.55757328, 0.6189414 , 0.76514993,
        0.48365085, 0.35762613, 0.8807984 , 0.96222669, 0.65310254,
        0.06791795, 0.73421459, 0.30026167, 0.14514145, 0.25058   ,
        0.63343412, 0.93009983, 0.55479294, 0.

## 기본 연산

In [58]:
np.sum(array_3d, axis=0)  # 0번 축을 기준으로 합하기

array([[1.68489643, 0.47868109, 1.26309192, 1.98537217, 1.31215504],
       [0.98824594, 0.89356576, 1.04116599, 1.55318655, 1.85128044],
       [0.75231741, 1.2614713 , 2.28909577, 2.48026132, 1.71014037],
       [1.0673246 , 1.95781446, 1.86244732, 1.24569198, 1.81597515],
       [1.83372781, 2.06513253, 0.99497275, 1.60106119, 1.59299011]])

In [59]:
np.sum(array_3d, axis=1)  # 1번 축을 기준으로 합하기

array([[2.19123469, 1.72010094, 3.14836448, 2.88232826, 2.61473559],
       [1.61693072, 2.41207305, 1.69979178, 3.26639664, 3.33180798],
       [2.51834678, 2.52449114, 2.60261749, 2.71684832, 2.33599754]])

In [60]:
np.sum(array_3d, axis=2)  # 2번 축을 기준으로 합하기

array([[3.23002735, 1.53028955, 2.09459753, 3.26005265, 2.44179688],
       [1.12409702, 1.99056679, 3.06128404, 3.19108521, 2.95996711],
       [2.37007229, 2.80658834, 3.33740461, 1.49811565, 2.68612039]])

In [24]:
np.mean(array_3d, axis=0)

array([[0.82468876, 0.29148638, 0.47373306, 0.87900965, 0.66314031],
       [0.70749891, 0.53262993, 0.59435545, 0.37490351, 0.53604614],
       [0.43861332, 0.2341969 , 0.85505017, 0.25000053, 0.38429103],
       [0.53980506, 0.35656865, 0.36460468, 0.71591918, 0.40135255],
       [0.15483886, 0.53850966, 0.39345034, 0.77654778, 0.52982679]])

In [61]:
np.min(array_3d, axis=0)

array([[0.09838673, 0.1300197 , 0.0846903 , 0.47121225, 0.16599771],
       [0.07855933, 0.16597771, 0.23564542, 0.25552162, 0.37138356],
       [0.09615487, 0.00526412, 0.69183316, 0.65333859, 0.36029251],
       [0.06791795, 0.24781776, 0.30026167, 0.14514145, 0.25058   ],
       [0.33666411, 0.44305729, 0.06109793, 0.20095063, 0.04846696]])

## 원소 단위 연산

In [28]:
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr2 = np.array([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
])

In [62]:
arr1 + arr2  # 원소끼리 더하기

array([[101, 102, 103],
       [204, 205, 206],
       [307, 308, 309]])

In [63]:
arr1 * arr2  # 원소끼리 곱하기

array([[ 100,  200,  300],
       [ 800, 1000, 1200],
       [2100, 2400, 2700]])

In [65]:
# broadcasting
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr2 = np.array([100, 200, 300])
# arr2 = np.array([
#     [100, 200, 300],
#     [100, 200, 300],
#     [100, 200, 300]
# ])
arr1 + arr2

array([[101, 202, 303],
       [104, 205, 306],
       [107, 208, 309]])

In [66]:
arr2 = np.array([
    [100],
    [200],
    [300]
])
# arr = np.array([
#     [100, 100, 100],
#     [200, 200, 200],
#     [300, 300, 300]
# ])
arr1 + arr2

array([[101, 102, 103],
       [204, 205, 206],
       [307, 308, 309]])

In [68]:
arr1**2  # 이런 것도 당연히 가능

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [70]:
arr1 / 2  # 이런 것도

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

## 행렬 연산

In [30]:
np.matmul(arr1, arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

# 편의 기능

In [73]:
np.zeros((3, 3, 3))  # 영행렬 만들기

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [81]:
np.ones((3, 3, 3))  # 일행렬 만들기

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [80]:
np.eye(3)  # I 행렬 만들기

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.random.random((3, 3, 3))  # 랜덤 행렬 만들기

array([[[0.53866565, 0.90419972, 0.79649846],
        [0.84400423, 0.41351767, 0.69882502],
        [0.3222055 , 0.17097523, 0.11099782]],

       [[0.67509692, 0.35757549, 0.00369842],
        [0.40386347, 0.00747354, 0.87190548],
        [0.46529451, 0.80062792, 0.64925452]],

       [[0.55258476, 0.08567168, 0.89016585],
        [0.88809778, 0.31211088, 0.83367328],
        [0.19783759, 0.87072307, 0.10780246]]])

이제 모르는 것이 있다면 구글에 검색하면 된다!

*E.O.D.*