# Numpy

In [2]:
import numpy as np

In [3]:
# 1차원 array 만들기
array_1d = np.array([1, 2, 3, 4, 5])
array_1d

array([1, 2, 3, 4, 5])

In [4]:
# 2차원 array 만들기
array_2d = np.array(
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ]
)
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
# 3차원 array 만들기
array_3d = np.random.random((3, 5, 5))
array_3d

array([[[0.7101576 , 0.93570943, 0.18347632, 0.77358467, 0.06764932],
        [0.53045791, 0.55590779, 0.55850787, 0.95506407, 0.89219324],
        [0.62895024, 0.65540772, 0.19512434, 0.52491084, 0.61608629],
        [0.4650145 , 0.8184758 , 0.11102471, 0.65989455, 0.46470637],
        [0.45087528, 0.46592663, 0.28484976, 0.60634748, 0.92472383]],

       [[0.44390993, 0.09851919, 0.84107886, 0.61493417, 0.67935845],
        [0.53659001, 0.2821142 , 0.6738786 , 0.17357622, 0.01676133],
        [0.44388665, 0.57921283, 0.44695904, 0.02741166, 0.0664772 ],
        [0.45543601, 0.97201685, 0.02987164, 0.70150406, 0.42454935],
        [0.03263834, 0.61787742, 0.80171774, 0.91501822, 0.98229007]],

       [[0.24314418, 0.67920145, 0.91269917, 0.47247692, 0.863069  ],
        [0.76336466, 0.50044498, 0.01079769, 0.66280918, 0.55419501],
        [0.37264681, 0.74931362, 0.88172612, 0.82542141, 0.04867379],
        [0.07351142, 0.49331644, 0.92004862, 0.42408071, 0.48150623],
        [0.91248

In [6]:
# array 모양 확인하기
array_3d.shape

(3, 5, 5)

In [7]:
# 차원 순서 바꾸기
np.transpose(array_3d, (1, 2, 0))

array([[[0.7101576 , 0.44390993, 0.24314418],
        [0.93570943, 0.09851919, 0.67920145],
        [0.18347632, 0.84107886, 0.91269917],
        [0.77358467, 0.61493417, 0.47247692],
        [0.06764932, 0.67935845, 0.863069  ]],

       [[0.53045791, 0.53659001, 0.76336466],
        [0.55590779, 0.2821142 , 0.50044498],
        [0.55850787, 0.6738786 , 0.01079769],
        [0.95506407, 0.17357622, 0.66280918],
        [0.89219324, 0.01676133, 0.55419501]],

       [[0.62895024, 0.44388665, 0.37264681],
        [0.65540772, 0.57921283, 0.74931362],
        [0.19512434, 0.44695904, 0.88172612],
        [0.52491084, 0.02741166, 0.82542141],
        [0.61608629, 0.0664772 , 0.04867379]],

       [[0.4650145 , 0.45543601, 0.07351142],
        [0.8184758 , 0.97201685, 0.49331644],
        [0.11102471, 0.02987164, 0.92004862],
        [0.65989455, 0.70150406, 0.42408071],
        [0.46470637, 0.42454935, 0.48150623]],

       [[0.45087528, 0.03263834, 0.91248551],
        [0.46592663, 0.617

In [8]:
# 모양 바꾸기
np.reshape(array_3d, (3, 25))

array([[0.7101576 , 0.93570943, 0.18347632, 0.77358467, 0.06764932,
        0.53045791, 0.55590779, 0.55850787, 0.95506407, 0.89219324,
        0.62895024, 0.65540772, 0.19512434, 0.52491084, 0.61608629,
        0.4650145 , 0.8184758 , 0.11102471, 0.65989455, 0.46470637,
        0.45087528, 0.46592663, 0.28484976, 0.60634748, 0.92472383],
       [0.44390993, 0.09851919, 0.84107886, 0.61493417, 0.67935845,
        0.53659001, 0.2821142 , 0.6738786 , 0.17357622, 0.01676133,
        0.44388665, 0.57921283, 0.44695904, 0.02741166, 0.0664772 ,
        0.45543601, 0.97201685, 0.02987164, 0.70150406, 0.42454935,
        0.03263834, 0.61787742, 0.80171774, 0.91501822, 0.98229007],
       [0.24314418, 0.67920145, 0.91269917, 0.47247692, 0.863069  ,
        0.76336466, 0.50044498, 0.01079769, 0.66280918, 0.55419501,
        0.37264681, 0.74931362, 0.88172612, 0.82542141, 0.04867379,
        0.07351142, 0.49331644, 0.92004862, 0.42408071, 0.48150623,
        0.91248551, 0.12807533, 0.18241782, 0.

## 기본 연산

In [9]:
np.sum(array_3d, axis=0)  # 0번 축을 기준으로 합하기

array([[1.3972117 , 1.71343007, 1.93725435, 1.86099576, 1.61007678],
       [1.83041258, 1.33846697, 1.24318416, 1.79144948, 1.46314958],
       [1.44548371, 1.98393417, 1.5238095 , 1.37774391, 0.73123728],
       [0.99396193, 2.28380909, 1.06094497, 1.78547932, 1.37076195],
       [1.39599913, 1.21187938, 1.26898532, 1.91890612, 2.79063389]])

In [10]:
np.sum(array_3d, axis=1)  # 1번 축을 기준으로 합하기

array([[2.78545553, 3.43142738, 1.332983  , 3.51980161, 2.96535904],
       [1.91246094, 2.54974048, 2.79350588, 2.43244434, 2.1694364 ],
       [2.36515258, 2.55035182, 2.90768942, 2.78232863, 2.83106403]])

In [11]:
np.sum(array_3d, axis=2)  # 2번 축을 기준으로 합하기

array([[2.67057734, 3.49213088, 2.62047943, 2.51911593, 2.73272297],
       [2.6778006 , 1.68292036, 1.56394738, 2.58337792, 3.34954178],
       [3.17059072, 2.49161152, 2.87778175, 2.39246342, 2.50413907]])

In [12]:
np.sum(array_3d)  # 전체 합하기

39.32920107145894

In [13]:
np.mean(array_3d, axis=0)

array([[0.46573723, 0.57114336, 0.64575145, 0.62033192, 0.53669226],
       [0.61013753, 0.44615566, 0.41439472, 0.59714983, 0.48771653],
       [0.4818279 , 0.66131139, 0.5079365 , 0.45924797, 0.24374576],
       [0.33132064, 0.7612697 , 0.35364832, 0.59515977, 0.45692065],
       [0.46533304, 0.40395979, 0.42299511, 0.63963537, 0.9302113 ]])

In [14]:
np.min(array_3d, axis=0)

array([[0.24314418, 0.09851919, 0.18347632, 0.47247692, 0.06764932],
       [0.53045791, 0.2821142 , 0.01079769, 0.17357622, 0.01676133],
       [0.37264681, 0.57921283, 0.19512434, 0.02741166, 0.04867379],
       [0.07351142, 0.49331644, 0.02987164, 0.42408071, 0.42454935],
       [0.03263834, 0.12807533, 0.18241782, 0.39754042, 0.88361999]])

## 원소 단위 연산

In [15]:
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr2 = np.array([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
])

In [16]:
arr1 + arr2  # 원소끼리 더하기

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [17]:
arr1 * arr2  # 원소끼리 곱하기

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [18]:
arr1 / arr2

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [19]:
# broadcasting
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr2 = np.array([100, 200, 300])
# arr2 = np.array([
#     [100, 200, 300],
#     [100, 200, 300],
#     [100, 200, 300]
# ])
arr1 + arr2

array([[101, 202, 303],
       [104, 205, 306],
       [107, 208, 309]])

In [20]:
# broadcasting 2
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr2 = np.array([
    [100],
    [200],
    [300]
])
# arr = np.array([
#     [100, 100, 100],
#     [200, 200, 200],
#     [300, 300, 300]
# ])
arr1 + arr2

array([[101, 102, 103],
       [204, 205, 206],
       [307, 308, 309]])

In [21]:
arr1**(1/2)  # 이런 것도 당연히 가능

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [22]:
arr1 / 2  # 이런 것도

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

## 행렬 연산

In [23]:
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr2 = np.array([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
])
np.matmul(arr1, arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

# 편의 기능

In [24]:
np.zeros((3, 3, 3))  # 영행렬 만들기

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
np.zeros_like(arr1)  # arr1 과 같은 shape의 영행렬 만들기

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
np.ones((3, 3, 3))  # 일행렬 만들기

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [27]:
np.eye(5)  # I 행렬 만들기

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.random((3, 3, 3))  # 랜덤 행렬 만들기

array([[[0.33652711, 0.14596162, 0.57082891],
        [0.10632926, 0.17696516, 0.8919381 ],
        [0.41751452, 0.90127455, 0.51460716]],

       [[0.3223207 , 0.3280134 , 0.02770667],
        [0.40203292, 0.55583294, 0.29758088],
        [0.72677193, 0.18619649, 0.49497439]],

       [[0.49022938, 0.90101835, 0.38775057],
        [0.54313419, 0.25149787, 0.21022881],
        [0.05073541, 0.31465662, 0.04836316]]])

이제 모르는 것이 있다면 구글에 검색하면 된다!

*E.O.D.*